name: Build and Push Docker Image with Model

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Configure AWS credentials
      run: |
        aws configure set aws_access_key_id 
        aws configure set aws_secret_access_key 

    - name: Download model from S3 (Yandex Object Storage)
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ru-central1
        AWS_EC2_METADATA_DISABLED: true
      run: |
        aws s3 cp s3://amamylov-mlops/hate_speech_detection/model/ backend_of_service/model/ --recursive --endpoint-url=https://storage.yandexcloud.net
      shell: bash

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./backend_of_service
        file: ./backend_of_service/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_TAG }}

    - name: Log out from Docker Hub
      run: docker logout
